### PR TITLE
Update faq.rst with information about ssh

### PR DESCRIPTION
**Pull request by aptiko**
Added question "I ran DebOps against a target host and now I can no
longer ssh into the host."

### CODE REVIEW

**Comment by aptiko** [comment]
BTW, should I put my name and my employer's name somewhere? My employer owns the copyright for this change. I took a look at the various files but I was a bit confused.

**Comment by drybjed** [comment]
@aptiko You can add yourself and your employer at the top of the file, with the `Copyright:` header.

**Comment by aptiko** [comment]
I added my employer to the `Copyright`.

**Review by drybjed — APPROVED** [review]
Nicely done, thanks. I'll backport it to the stable releases.

**Pull request merged**
