### PR TITLE
[apparmor] Convert to universal configuration and move from contrib

### PR DESCRIPTION
**Pull request by Alphix**
This (quite lightly tested) pull request modernises the apparmor role and moves it from contrib to the official list of roles.

This, in turn, allows apparmor to be used as a dependency for other roles, which allows us to fix various issues caused by the combination of apparmor and customizations made by DebOps roles (e.g. `/etc/pki` for SSL/TLS certs).

This should address at least:
#1171
#690
#456

And is also a prerequisite for another role I'm working on (`bind`).

### CODE REVIEW

**Comment by Alphix** [comment]
Note that this PR doesn't add `apparmor` to the `common` playbook yet...

Also: once the PR has been approved, we need to:
* add integration to `slapd`
* add integration to `apt_cacher_ng` and remove `debops-contrib-playbooks/service/apt_cacher_ng.yml`
* add integration to `dnsmasq` and remove `debops-contrib-playbooks/service/dnsmasq.yml`

**Comment by Alphix** [comment]
Merged some of the fixups with their parent commits and also rebased this PR on top of #2214 so that the CI checks can be performed properly.

**Comment by Alphix** [comment]
Rebased, fixing conflicts and also squashed the fixup patches with the parent patches

**Review by drybjed — APPROVED** [review]
Great job with the migration, thank you! I agree that this role needs to be in the common playbook, but let's merge it first and test in the wild to make sure it doesn't break different environments.

**Comment by ypid** [comment]
#2325 includes a small fix. Otherwise awesome work @Alphix! I only did a review and light testing for now.

Edit: Ah, #2319 already fixes the bug I found :)

**Pull request merged**
