### PR TITLE
[doc] Various minor edits

### PR DESCRIPTION
**Pull request by tasosalvas**
I tried to buffer a few fixes like ypid does, ended up having to fix typos on previous commits.

I also wanted to wait before publishing my url on credits, but I'm in week 2 of a planned 2 day crunch so I think I'll let my debops welcome page fly proud for now :D

All feedback welcome

### CODE REVIEW

**Comment by drybjed** [comment]
@tasosalvas Thanks for the PR. I reworder some documentation and made a separate PR against your repository, what do you think about the change? You can merge it into your branch, then the changes will be added to your pull request.

**Comment by tasosalvas** [comment]
I liked the warning box, as it signified that chunk of text as an aside, but I guess we don't use them anywhere else atm.

Similarly I kept the description brief as it was towards the end of the role's doc, where we can expect people to need the least hand-holding. Yours is well written and more explanatory, though.

**Comment by tasosalvas** [comment]
I was doing `-S` with all my commits, I don't get how they ended up unsigned.

**Comment by drybjed** [comment]
I'm not sure why GPG signatures were not added to the commits. I just have this configured in my global ` ~/.gitconfig` file so that I don't need to use `-S` specifically. All my `git` commits are always signed due to this, but it's a small price to pay for consistency.

**Review by drybjed — APPROVED** [review]
Thanks for the updates.

**Pull request merged**
