### PR TITLE
update unattended upgrade reciepe for bullseye

### PR DESCRIPTION
**Pull request by bleuchtang**

### CODE REVIEW

**Comment by tumd** [comment]
The default `50unattended-upgrades` file looks like this;
```
Unattended-Upgrade::Origins-Pattern {
        // Codename based matching:
        // This will follow the migration of a release through different
        // archives (e.g. from testing to stable and later oldstable).
        // Software will be the latest available for the named release,
        // but the Debian release itself will not be automatically upgraded.
//      "origin=Debian,codename=${distro_codename}-updates";
//      "origin=Debian,codename=${distro_codename}-proposed-updates";
        "origin=Debian,codename=${distro_codename},label=Debian";
        "origin=Debian,codename=${distro_codename},label=Debian-Security";
        "origin=Debian,codename=${distro_codename}-security,label=Debian-Security";
```
I'm not entirely sure what's the difference between the last to posts, but my assumption ("[guy-guessing](https://en.wiktionary.org/wiki/killgissa)") is that rolling security fixes gets into `codename=${distro_codename}-security` to push such fixes out quickly, and that these patched packages get moved to `${distro_codename}` at each point-release.

Perhaps this PR should include `origin=Debian,codename=${distro_codename},label=Debian-Security` too?

**Comment by bleuchtang** [comment]
My Guess is that `origin=Debian,codename=${distro_codename},label=Debian-Security` will be never be used regarding `apt-cache policy` output. This is my output on a fresh bullseye deployed with debops (including apt role):
```
Package files:
 100 /var/lib/dpkg/status
     release a=now
 500 http://security.debian.org bullseye-security/main amd64 Packages
     release v=11,o=Debian,a=stable-security,n=bullseye-security,l=Debian-Security,c=main,b=amd64                                                                                                
     origin security.debian.org
 100 http://deb.debian.org/debian bullseye-backports/main amd64 Packages
     release o=Debian Backports,a=bullseye-backports,n=bullseye-backports,l=Debian Backports,c=main,b=amd64                                                                                      
     origin deb.debian.org
 500 http://deb.debian.org/debian bullseye-updates/main amd64 Packages
     release v=11-updates,o=Debian,a=stable-updates,n=bullseye-updates,l=Debian,c=main,b=amd64
     origin deb.debian.org
 500 http://deb.debian.org/debian bullseye/main amd64 Packages
     release v=11.1,o=Debian,a=stable,n=bullseye,l=Debian,c=main,b=amd64
     origin deb.debian.org
```

**Comment by tumd** [comment]
Yeah, you are probably right.
The reason for keeping both seem to be backwards compatibility. See upstream [commit](https://github.com/mvo5/unattended-upgrades/commit/86ee50f03bb14ecfacf18cd1ce51208c6521e755).

If it isn't disruptive in any way, adding this last line to the existing "Debian"-key would probably be best. I don't _think_ that should cause any harm.

**Comment by bleuchtang** [comment]
> If it isn't disruptive in any way, adding this last line to the existing "Debian"-key would probably be best. I don't _think_ that should cause any harm.

Done :)

**Review by imrejonk — APPROVED** [review]
Thanks for this PR, I didn't think about updating my unattended-upgrades configuration with the new security repository name. It's a good thing to keep automatic security updates going.

@tumd you are right about the updates in stable-security getting moved to stable during a point release. stable-security is only for important security fixes; less important fixes are introduced through stable-proposed-updates and get moved to stable during the point release as well.

**Comment by bleuchtang** [comment]
Any news ?

**Review by drybjed — APPROVED** [review]
Looks good, thanks. I'll make a backport to the stable releases as well.

**Pull request merged**
