### PR TITLE
fix(sshd): use "init" for parameter to uncomment when set

### PR DESCRIPTION
**Pull request by ypid**
Did I miss something about https://docs.debops.org/en/master/user-guide/universal-configuration.html#universal-configuration? I know that you use `comment` in other roles as well.

### CODE REVIEW

**Review by drybjed — APPROVED** [review]
Looks good. And the `init` state works correctly in cases were complex syntax is used, uncommenting options as needed, so let's go with it instead.

**Comment by ypid** [comment]
You are welcome. I am done with testing of the redesigned sshd role. Nice job! I finally start to appreciate universal configuration. I updated my inventory presets:

* https://github.com/ypid/ypid-ansible-inventory/blob/master/group_vars/public_ypid_defaults_debops/public_ypid_defaults_debops_sshd.yml
* https://github.com/ypid/ypid-ansible-inventory/blob/master/group_vars/public_ypid_paranoid_debops/public_ypid_paranoid_debops_sshd.yml

Accordingly.

**Comment by julien-lecomte** [comment]
@ypid There's an extra space line 32 of file #2 : 'DisableForwarding '

**Comment by ypid** [comment]
Thanks @drybjed and @julien-lecomte, fixed (https://github.com/ypid/ypid-ansible-inventory/issues/1). It actually worked because DisableForwarding is not defined in DebOps. I was a bit tired yesterday evening :)

**Pull request merged**
