### PR TITLE
[Vagrant] add VAGRANT_NODE_BOX variable in comments

### PR DESCRIPTION
**Pull request by nqb**

### CODE REVIEW

**Comment by nqb** [comment]
@drybjed, do you plan to move from debian/stretch64 to debian/buster64 ?

**Comment by drybjed** [comment]
Yes, I saw that `debian/buster64` libvirt image was updated 2 days ago or so, therefore I'll look into switching to it soon, probably this weekend. I wish that the LXC images could get the same treatment, but it looks like they are abandoned at the moment?

**Review by drybjed — APPROVED** [review]

**Comment by nqb** [comment]
> Yes, I saw that `debian/buster64` libvirt image was updated 2 days ago or so, therefore I'll look into switching to it soon, probably this weekend.

Good to know.

>  I wish that the LXC images could get the same treatment, but it looks like they are abandoned at the moment?

IIRC, yes but I was not able to find any information on this subject.

**Comment by nqb** [comment]
Maybe @EmmanuelKasper can give us a status or a pointer about Vagrant LXC images for Buster.

**Comment by drybjed** [comment]
Actually, I wonder if the LXC images for Vagrant would be unprivileged or not (I think not). This could impact things, since `debops.lxc` by default is designed to work with unprivileged, downloaded images, which are  pulled via the `lxc-download` template. I'm not sure if `vagrant-lxc` plugin would support these unprivileged images built by LXC upstream, would be interesting if it did.

**Comment by EmmanuelKasper** [comment]
No one is working at the moment building LXC base boxes.
 I didn't manage to uild them last time I tried. 
You can have a try at https://salsa.debian.org/cloud-team/vagrant-boxes/tree/master/custom-lxc-vagrant and report on the debian cloud mailing list.

**Comment by nqb** [comment]
Thanks for feedback @EmmanuelKasper.

**Pull request merged**
