### PR TITLE
Add pipeline to run with latest ansible-lint

### PR DESCRIPTION
**Pull request by ssbarnea**
Related: https://github.com/ansible/ansible-lint/discussions/1403#discussioncomment-2654415

### CODE REVIEW

**Review by drybjed — DISMISSED** [review]
Looks good. I'll add the missing SPDX headers.

**Comment by drybjed** [comment]
@ssbarnea Are you sure that the linting process does anything? DebOps has its own `ansible-lint` test and it takes 5 minutes, also `ansible-lint` detects the playbooks and roles:
```
WARNING  Loading custom .yamllint config file, this extends our internal yamllint config.
INFO     Discovered files to lint using: git ls-files --cached --others --exclude-standard -z
INFO     Excluded removed files using: git ls-files --deleted -z
INFO     Discovered files to lint using: git ls-files --cached --others --exclude-standard -z
INFO     Excluded removed files using: git ls-files --deleted -z
INFO     Executing syntax check on ansible/playbooks/bootstrap-ldap.yml (1.56s)
INFO     Executing syntax check on ansible/playbooks/agent.yml (1.47s)
INFO     Executing syntax check on ansible/playbooks/virt.yml (3.42s)
INFO     Executing syntax check on ansible/roles/volkszaehler/docs/playbooks/volkszaehler-nginx.yml (0.87s)
INFO     Executing syntax check on docs/ansible/roles/kibana/examples/application-playbook.yml (0.70s)
INFO     Executing syntax check on ansible/playbooks/env.yml (1.89s)
INFO     Executing syntax check on ansible/roles/foodsoft/docs/playbooks/foodsoft-nginx.yml (0.79s)
INFO     Executing syntax check on docs/ansible/roles/rabbitmq_server/examples/application-playbook.yml (0.70s)
INFO     Executing syntax check on ansible/playbooks/bootstrap.yml (1.15s)
INFO     Executing syntax check on ansible/roles/volkszaehler/docs/playbooks/volkszaehler.yml (1.15s)
INFO     Executing syntax check on ansible/roles/volkszaehler/docs/playbooks/volkszaehler-apache.yml (0.87s)
INFO     Executing syntax check on ansible/roles/bitcoind/docs/playbooks/bitcoind.yml (0.72s)
INFO     Executing syntax check on ansible/roles/x2go_server/docs/playbooks/x2go_server.yml (0.51s)
INFO     Executing syntax check on ansible/roles/firejail/docs/playbooks/firejail.yml (0.52s)
INFO     Executing syntax check on ansible/roles/snapshot_snapper/docs/playbooks/snapshot_snapper.yml (0.53s)
INFO     Executing syntax check on ansible/roles/dropbear_initramfs/docs/playbooks/dropbear_initramfs.yml (0.53s)
INFO     Executing syntax check on ansible/roles/fuse/docs/playbooks/fuse.yml (0.52s)
INFO     Executing syntax check on ansible/roles/btrfs/docs/playbooks/btrfs.yml (0.50s)
INFO     Executing syntax check on ansible/playbooks/bootstrap-sss.yml (1.48s)
INFO     Executing syntax check on ansible/roles/foodsoft/docs/playbooks/foodsoft.yml (0.79s)
INFO     Executing syntax check on docs/ansible/roles/etc_aliases/examples/application-playbook.yml (0.68s)
INFO     Executing syntax check on ansible/playbooks/common.yml (2.05s)
INFO     Executing syntax check on ansible/playbooks/app.yml (7.37s)
INFO     Executing syntax check on docs/ansible/roles/postfix/examples/application-playbook.yml (0.73s)
INFO     Executing syntax check on docs/ansible/roles/elasticsearch/examples/application-playbook.yml (0.72s)
INFO     Executing syntax check on ansible/playbooks/sys.yml (3.45s)
INFO     Executing syntax check on ansible/playbooks/hw.yml (0.84s)
INFO     Executing syntax check on docs/ansible/roles/console/playbooks/console.yml (0.51s)
INFO     Executing syntax check on ansible/playbooks/net.yml (3.18s)
INFO     Executing syntax check on ansible/playbooks/srv.yml (14.15s)
INFO     Executing syntax check on ansible/roles/apparmor/docs/playbooks/apparmor.yml (0.69s)
INFO     Executing syntax check on ansible/playbooks/site.yml (34.61s)
```
But I don't see it happening in the new `ansible-lint` test using the `main` branch, and the test itself finishes in 1 minute:
```
INFO     Discovered files to lint using: git ls-files --cached --others --exclude-standard -z
INFO     Excluded removed files using: git ls-files --deleted -z
DEBUG    Excluded .gitlab-ci.yml (yaml)
DEBUG    Examining .readthedocs.yml of type yaml
DEBUG    Examining .github/workflows/continuous-integration.yml of type yaml
DEBUG    Examining .ansible-lint of type yaml
DEBUG    Examining .github/workflows/ansible-lint.yml of type yaml
DEBUG    Examining . of type role
DEBUG    Examining .yamllint of type yaml
DEBUG    Examining .github/workflows/debops-ci-pipeline.yml of type yaml
DEBUG    Examining .github/workflows/prepare-ci-pipeline/action.yml of type yaml
DEBUG    Examining .github/workflows/super-linter.yml of type yaml
```
The existing test just runs `ansible-lint -v` in the main repository directory. Any clues as to why the two tests behave differently?

**Comment by drybjed** [comment]
@ssbarnea Can you rebase this PR on the latest changes in the `master` branch to see what else needs to be fixed?

**Comment by ssbarnea** [comment]
@drybjed Rebased, basically if you add `dpkg_divert` to mock_modules you can make it report green. Still, that mocking is bad/evil.

What you really need to do is to ensure that `dpkg_divert` module is part of the collection itself and call it using the full notation `debops.debops.dpkg_divert`.

**Comment by drybjed** [comment]
> @drybjed Rebased, basically if you add `dpkg_divert` to mock_modules you can make it report green. Still, that mocking is bad/evil.
> 
> What you really need to do is to ensure that `dpkg_divert` module is part of the collection itself and call it using the full notation `debops.debops.dpkg_divert`.

I think that `dpkg_divert` should be a part of the DebOps collection already, I'm not sure why it's not detected by `ansible-lint`. Do I need to add `__init__.py` in the `ansible/plugins/modules/` directory for that to be the case?

Also, I don't think that `ansible-lint` in the new workflow even touches DebOps codebase in `ansible/` directory. The new workflow runs for 14 seconds, while the old workflow with `ansible-lint` runs for 4 minutes 18 seconds. Any idea why this happens?

**Comment by drybjed** [comment]
After some investigation, we managed to make `ansible-lint` detect the DebOps repository correctly. However, since the GHA workflow uses `ansible-lint` that's already released, same as the current workflow in `continuous-integration.yml`, adding this one would result in running the same test twice. I'm closing this PR due for this reason - using `ansible-lint` from the `main` branch to test future changes before a new release is made might be considered in the future.

**Pull request closed without merging**
