### PR TITLE
[debops.lxc] port latest connection plugin lxc_ssh.py

### PR DESCRIPTION
**Pull request by stefangweichinger**
Latest release of ansible connection plugin lxc_ssh.py from

https://github.com/andreasscherbaum/ansible-lxc-ssh

commit be72f62c5b5ef766e917c375666516835bcda733

### CODE REVIEW

**Comment by drybjed** [comment]
@stefangweichinger Can I merge this now, or are you waiting for some more changes?

**Comment by stefangweichinger** [comment]
@drybjed From my point of view it's OK. I checked https://github.com/andreasscherbaum/ansible-lxc-ssh/issues right now, no new problems today ... so it should work.

**Review by drybjed — APPROVED** [review]
Thanks for porting the latest release, I'll backport it to the stable DebOps releases as well.

**Comment by stefangweichinger** [comment]
> Thanks for porting the latest release, I'll backport it to the stable DebOps releases as well.

Thanks for the merge, let's see how it works for the users.

**Pull request merged**
