### PR TITLE
added missing note on task-paths

### PR DESCRIPTION
**Pull request by damko**

### CODE REVIEW

**Comment by drybjed** [comment]
@damko Thanks for working on the documentation! Could you rebase your PR on the current `master` branch? It should fix tests that fail due to `pipefail` requirement.

**Comment by damko** [comment]
@drybjed did I do this right?

**Comment by drybjed** [comment]
@damko No, you should first pull the `master` branch of `debops/debops` to your fork. Then, make a new branch off of it and push it to this PR instead. Don't create branches off of the `latest` branch, it points to the latest released version, you should use `master` instead.

**Comment by drybjed** [comment]
Oops, I didn't mean to close this... @damko, do you still have the changes? I wasn't able to find them in your fork, I guess you deleted the branch. Do you plan to create a new PR?

**Comment by damko** [comment]
I didn't touch anything yet. To be honest after reading your last comment I was thinking to simply update master and push there the change instead of fixing this PR. Does it make sense?

**Comment by drybjed** [comment]
Sure, you can. Although I'm usually creating a new branch for a given feature. Then you can just create a new PR that should be sane. :-)

**Pull request closed without merging**
