### PR TITLE
DebOps for Ansible users: correct typos

### PR DESCRIPTION
**Pull request by arturmartins**
Grammarly identified 30 issues, but I only corrected the critical ones.

### CODE REVIEW

**Review by drybjed — APPROVED** [review]
Thanks, this is greatly appreciated. :-)

**Comment by drybjed** [comment]
It seems that you created this PR against an older version, can you pull latest changes from the [`debops/debops`](https://github.com/debops/debops/) `master` branch, rebase your PR on them and push with `--force` to your branch? That should update the PR with latest fixes to the Travis-CI tests.

**Comment by arturmartins** [comment]
Sure thing. Apologies for this.

**Comment by drybjed** [comment]
I'll merge this PR after rebasing on the current `master`, sorry it took so long. :-)

**Comment by drybjed** [comment]
This PR was merged as https://github.com/debops/debops/commit/5a717f3a99a33ff52cb0936296a6d2405bdb37c6, closing.

**Pull request closed without merging**
