### PR TITLE
[rspamd] Add new role

### PR DESCRIPTION
**Pull request by Alphix**
Rspamd is an advanced spam filtering system that allows evaluation of messages
by a number of rules including regular expressions, statistical analysis and
custom services such as URL black lists. Each message is analysed by Rspamd and
given a spam score.

According to this spam score and the user’s settings, Rspamd recommends an
action for the MTA to apply to the message, for example, to pass, reject or add
a header. Rspamd is designed to process hundreds of messages per second
simultaneously, and provides a number of useful features.

Rspamd also includes a web-based UI.

This role features integration with debops.postfix, debops.redis, debops.nginx,
etc, allowing for a working configuration out-of-the-box.

Partially based on: https://gitlab.com/ciphermail/debops.rspamd

With some manual configuration, DKIM generation/rotation is also supported,
even with automatic DNS updates (after the initial manual setup).

### CODE REVIEW

**Comment by imrejonk** [comment]
Wow, thanks for taking the time and effort to make something out of my half-arsed rspamd role! Will take a look next week. The timing is perfect as I’m currently working on my employer’s email setup, as you surely know :)

**Comment by Alphix** [comment]
> Wow, thanks for taking the time and effort to make something out of my half-arsed rspamd role! Will take a look next week. The timing is perfect as I’m currently working on my employer’s email setup, as you surely know :)

@imrejonk I kind of started the role from scratch many months ago, then finally got around to finishing it this month (writing docs, etc). Found your rspamd role by coincidence when I was almost done, and then incorporated a few ideas from there (supporting ``overrides.d`` as well as ``local.d``, using a few more dependent roles like ``debops.etc_services`` and ``debops.nginx`` and I really like how you handled ``rspamd__controller_password``).

Anyway, the role should be feature-complete now as far as I can tell. What's missing is more testing, which I haven't gotten around to yet, and that's why this is still a draft.

**Review by drybjed — APPROVED** [review]
Nice work, thanks! I'll add a gitlab-ci test and fix conflicts, so that this can be merged cleanly.

**Comment by imrejonk** [comment]
@Alphix Wow, didn't expect to see this role in DebOps 3.0! Congratz :tada: 
I'm sorry that I didn't review it before the merge. I'm currently keeping myself busy with a large migration at work. Know that I am very eager to replace [CipherMail's `debops.rspamd`](https://gitlab.com/ciphermail/debops.rspamd) with yours, but it will take some time to test all the changes between stable-2.3 and stable-3.0. I'll post an update here once that is done.

**Comment by Alphix** [comment]
> @Alphix Wow, didn't expect to see this role in DebOps 3.0! Congratz tada I'm sorry that I didn't review it before the merge. I'm currently keeping myself busy with a large migration at work. Know that I am very eager to replace [CipherMail's `debops.rspamd`](https://gitlab.com/ciphermail/debops.rspamd) with yours, but it will take some time to test all the changes between stable-2.3 and stable-3.0. I'll post an update here once that is done.

@imrejonk - since the role is already merged, you could also just post any changes/fixes/corrections you'd like to see as a separate PR.

**Pull request merged**
