### PR TITLE
Add debops.secret dependency to debops.gitlab_runner

### PR DESCRIPTION
**Pull request by rei-ifesca**
Allow to store the Runner Token and Runner API Token in the secret folder.

Example:

```
gitlab_runner__token: '{{ lookup("password", secret
                           + "/credentials/" + ansible_fqdn
                           + "/gitlab/runner/token chars=ascii,numbers") }}'
gitlab_runner__api_token: '{{ lookup("password", secret
                           + "/credentials/" + ansible_fqdn
                           + "/gitlab/runner/api_access_token chars=ascii,numbers") }}'
```

### CODE REVIEW

**Comment by rei-ifesca** [comment]
@drybjed maybe do you have an idea on how to ask the user (prompt?) during installation for the API tokens and store the tokens in the secret folder.

**Review by drybjed — CHANGES_REQUESTED** [review]
Sounds good, although I would remove the `tags` keyword, it's not needed in this case.

Could you add an example about this usage in the Token section of the documentation? It will be more discoverable this way.

**Comment by drybjed** [comment]
@rei-ifesca As for your question, I don't want to add any prompts to DebOps roles, the inventory is a good enough, and idempotent interface. Good documentation should be sufficient.

**Comment by rei-ifesca** [comment]
> @rei-ifesca As for your question, I don't want to add any prompts to DebOps roles, the inventory is a good enough, and idempotent interface. Good documentation should be sufficient.

I understnad.

Updated the `GitLab CI registration token` documentation.

**Review by drybjed — APPROVED** [review]

**Pull request merged**
