### PR TITLE
[WIP] Improve Getting Started guide and bootstrap usage

### PR DESCRIPTION
**Pull request by nqb**
- Move some links from latest to master, see #833
- Put Getting Started guide in Introduction section

### CODE REVIEW

**Comment by drybjed** [comment]
The error on Travis-CI:
```
/home/travis/build/debops/debops/docs/introduction/getting-started.rst:6:Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: '../includes/global.rst'
```
Not sure why that happens. Perhaps you could just remove the import line? I'm not sure if there are any references from the `includes/global.rst` in this document.

**Comment by nqb** [comment]
@drybjed, I saw error yesterday and fix it this morning. Error was due to the fact I move guide under `introduction`.

I was sure it was not necessary to include `global.rst` in this document because it's done in `docs/index.rst` but according to last error, it seems necessary.

**Comment by drybjed** [comment]
@nqb Looks good so far, do you want to make any more changes, or is the PR ready for a merge?

**Comment by nqb** [comment]
Hello @drybjed,

More changes to come this week.

**Review by drybjed — APPROVED** [review]
Thanks for refreshing the documentation. :-)

**Pull request merged**
