### PR TITLE
[gunicorn] Add secret role

### PR DESCRIPTION
**Pull request by thiras**
I've tried to integrate the secret role into gunicorn playbook. I've taken minio playbook as en example since it's relatively newly written.

### CODE REVIEW

**Comment by thiras** [comment]
I'm not sure if both pre role and role are required but nevertheless it worked for my case.

**Comment by thiras** [comment]
I've noticed that the playbook runs twice with a secret role as pre_task. So I've removed it.

**Comment by drybjed** [comment]
You should add the `secret` role in the task list instead, via the `import_role` Ansible module - see [the example in the `minio` role](https://github.com/debops/debops/blob/master/ansible/roles/minio/tasks/main.yml#L9-L10). That way users don't have to remember about including the `secret` role in all playbooks that use the `gunicorn` role.

**Review by drybjed — APPROVED** [review]
The change looks OK, not sure why Travis-CI does not want to test this PR now. I'll cherry pick the final commit to have a cleaner history. Thanks!

**Pull request closed without merging**
