### PR TITLE
[debops.influxdb] Add debops.influxdb role

### PR DESCRIPTION
**Pull request by LeonardoAndrei**

### CODE REVIEW

**Comment by scibi** [comment]
Hi!

I would suggest spliting this role to two roles: `influxdb_server` used to install server and `influxdb` used to manage users and databases. Just like `postgresql` and `postgresql_server`.

**Comment by alinalexandru** [comment]
Wi'll do that. Good idea

**Comment by pedroluislopez** [comment]
Hi, also I have developed influxdb role. You can see this here:
https://github.com/Neuromobile/debops/tree/influxdb
If you want, I can do a PR for review.

**Comment by alinalexandru** [comment]
@pedroluislopez I see the final version as a mix between this 2 solutions.

You can get the `parse_kv_config` from our role. Please add `validate_certs`, as it wont work with internal PKI.
The influxDB client from ansible those not support to specify the CA.
I will want to submit a PR to ansible to add that support.

Also enabling the authentication by default will break the creation of the first admin. At least when we wrote the role. From what I inspect, the problem was that the ansible function tries to get all the users, but until the first admin is created, only the create admin command is permitted.

**Comment by scibi** [comment]
@alinalexandru Do you need any help with spliting this role?

**Comment by drybjed** [comment]
@scibi: I believe that @pedroluislopez and @alinalexandru will want to combine their roles, not sure yet what will get mixed in the final role. Perhaps you three could work together on this?

I suppose that coordinating changes could be a problem. I added all three of you to the DebOps organization, can one of you try and push a new branch in the `debops/debops` repository based on `master`? Then you should be able to work together in it on the InfluxData roles. Probably one branch per application would be eaiser to merge later.

**Comment by pedroluislopez** [comment]
Maybe I can make a PR and make changes `parse_kv_config` based.

About `validate_certs`: maybe i can make a PR to ansible, but in the meantime i can upload custom plugins in ansible_plugins role in DebOps.

I enable authentication by default. In the first install, before enable authentication, i create the admin user and then I apply the configuration enabling authentication. This code:

```
- name: Restart database server on first install (influx bug)
  service:
    name: 'influxdb'
    state: 'restarted'
  when: ((influxdb_server__register_version|d() and not influxdb_server__register_version.stdout) and
         (influxdb_server__register_install_status|d() and influxdb_server__register_install_status is changed))

- name: Wait for HTTP endpoint port to become open on the host on first install
  wait_for:
    port: '{{ influxdb_server__http_endpoint_port }}'
  when: ((influxdb_server__register_version|d() and not influxdb_server__register_version.stdout) and
         (influxdb_server__register_install_status|d() and influxdb_server__register_install_status is changed))

- name: Create default admin user on first install
  influxdb_user:
    user_name: 'root'
    user_password: '{{ influxdb_server__root_password }}'
    state: 'present'
    admin: 'yes'
  when: ((influxdb_server__register_version|d() and not influxdb_server__register_version.stdout) and
         (influxdb_server__register_install_status|d() and influxdb_server__register_install_status is changed))

- name: Stop database server on first install
  service:
    name: 'influxdb'
    state: 'stopped'
  when: ((influxdb_server__register_version|d() and not influxdb_server__register_version.stdout) and
         (influxdb_server__register_install_status|d() and influxdb_server__register_install_status is changed))
```

The other users are created in the influxdb (client) role. The playbook is executed after influxdb_server role:

```
- import_playbook: influxdb_server.yml

- import_playbook: influxdb.yml
```

**Comment by pedroluislopez** [comment]
PR with mixed role: https://github.com/debops/debops/pull/1282

I've included @alinalexandru an other in Copyrights.

**Comment by ypid** [comment]
I am closing this PR now that #1282 is merged. Thanks to everyone who is involved in the roles!

**Pull request closed without merging**
