### PR TITLE
[debops.grub] Re-introduce grub__timeout_* variables removed in #466

### PR DESCRIPTION
**Pull request by ypid**
I found/find them quite useful to make precise changes in the inventory.

https://github.com/ypid/ypid-ansible-inventory/search?q=grub&unscoped_q=grub

Updates: #466

### CODE REVIEW

**Comment by drybjed** [comment]
They way to handle that now would be something like this in the inventory:
```
grub__configuration:
  - timeout: 10
```
But sure, I guess they can be exposed in separate variables.

**Review by drybjed — APPROVED** [review]

**Comment by ypid** [comment]
@drybjed How would I make changes only to hardware or virtual in the group inventory with this? I only want to change either hardware or virtual. I do this quite a bit in my inventory.

**Comment by drybjed** [comment]
@ypid Have separate groups for hardware and virtual hosts, and put `grub__group_configuration` in each with desired value. It can be a bit tricky if you want to change something more though at the group level, you would need to do some list contatenation tricks in the inventory.

**Comment by ypid** [comment]
Thanks for merging. I guess with those variables, it will be the simplest.

**Pull request merged**
