### PR TITLE
Import 'debops-contrib.etckeeper' role as 'debops.etckeeper'

### PR DESCRIPTION
**Pull request by drybjed**

### CODE REVIEW

**Review by ypid — CHANGES_REQUESTED** [review]
LGTM, very well done design! I reworked the Python script a bit in https://github.com/drybjed/debops/pull/3. Please merge.

**Comment by drybjed** [comment]
@ypid Updates merged, can you check the PR again?

**Review by ypid — APPROVED** [review]
The only changes since my last review are from me/signed by me so I approve them :) Sorry for the delay.

**Comment by drybjed** [comment]
Awesome, thanks!

**Pull request merged**
