### PR TITLE
[debops.bootstrap] Remove host/domain config

### PR DESCRIPTION
**Pull request by drybjed**
The configuration of the hostname and domain is removed from the
'debops.bootstrap' role and delegated to the 'debops.netbase' role,
included in the 'bootstrap.yml' playbook.

### CODE REVIEW

**Comment by ypid** [comment]
I will check in a few days.

**Comment by drybjed** [comment]
OK, it can wait a bit to be merged.

**Comment by ypid** [comment]
I guess it is fine when you just merge without my review because I am currently not able to provide a good review in time. I still review all changes to DebOps, with some weeks delay. Sorry for that.

**Comment by drybjed** [comment]
I apologize - perhaps I'm not patient enough sometimes. I specifically requested a review from you and then after waiting a week merged anyway. Instead, I should have asked you when do you plan to do the review and then wait for it knowing the time-frame. I will try to keep that in mind the next time.

**Pull request merged**
