### PR TITLE
Install debops from PyPI if /vagrant not mounted

### PR DESCRIPTION
**Pull request by nqb**
Related to #1061

### CODE REVIEW

**Comment by drybjed** [comment]
Thanks! Looks good, however I'll test it in a few hours before merging.

**Review by drybjed — APPROVED** [review]
Looks like the changes work nicely. Thanks!

**Comment by nqb** [comment]
The only drawback I saw is when you have run for example:
```
DEBOPS_FROM=pypi vagrant up
```
and after a halt of your VM, you run `vagrant up`. 

Provisioning will try to build `debops` from devel with an already installed `debops` from PyPI, we need to handle this case from my point of view.

**Comment by drybjed** [comment]
How about:
```
export DEBOPS_FROM="pypi"
```
That should ensure a consistent environment for the duration of a given session.

**Comment by nqb** [comment]
> How about:
> 
> ```
> export DEBOPS_FROM="pypi"
> ```

You mean on command-line when you run `vagrant up` for the first time ?

**Comment by drybjed** [comment]
Yes, exactly. The variable will be available during a given session, so you don't need to specify it each time `vagrant` command is executed.

**Pull request merged**
