### PR TITLE
feat(owncloud): Add support for NC20; Drop NC19 and oC support

### PR DESCRIPTION
**Pull request by ypid**
Please wait with merging, I am still in the process of upgrading my instances.

@Gomez, @SuperSandro2000, @pedroluislopez, you worked on ownCloud support a year ago. Do you still need oC support? If yes, can you check the updated Nginx config?

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
I never used owncloud and don't plan to use it.

**Comment by drybjed** [comment]
@ypid, let me know when the PR is ready for merge.

**Comment by ypid** [comment]
Ready.

**Review by drybjed — APPROVED** [review]
Great work as always, thank you! :-)

**Pull request merged**
