### PR TITLE
[ntp] Don't try to disable systemd-timesyncd if not available

### LINKED ISSUE #1422: ntp: "Could not find the requested service systemd-timesyncd" when using chrony
In my inventory I define `ntp__daemon: chrony` 

Now the `debops.ntp` role will fail when trying to "disable" systemd-timesyncd on a Debian Buster host:
```
TASK [debops.ntp : Manage systemd-timesyncd state] ***********************************************************************************
fatal: [host.example.com]: FAILED! => {"changed": false, "msg": "Could not find the requested service systemd-timesyncd: host"}
```

There is no `systemd-timsyncd.service` available on this host.

### PR DESCRIPTION
**Pull request by ganto**
Fixes #1422

### CODE REVIEW

**Comment by nqb** [comment]
Just for my knowledge, in which case systemd-timesyncd is not available ?

**Comment by ganto** [comment]
No idea... on the host I preseeded myself, there is no systemd-timesyncd.

**Comment by drybjed** [comment]
The condition is redundant with a check for `systemd` init. In my environment which uses unprivileged LXC containers, `systemd-timesyncd.service` unit is still present in the container even though the service is not running. The service file comes with the `systemd` package so it will probably be defined everywhere that `systemd` is used.

@ganto, can you tell a bit more details about your environment? What do you use to deploy it, is `systemd` used there?

**Comment by ganto** [comment]
> can you tell a bit more details about your environment? What do you use to deploy it, is systemd used there?

It's a KVM virtual machine that I installed in March 2019 via a minimal `ganto.libvirt-machine` Ansible role that is using `virt-install` with a locally mirrored Debian installer (at that time it was still Sarge) and a generated preseed.cfg (I completely forgot about this role, so I never uploaded it to github) but it looks more or less like [this](https://github.com/inofix/common-playbooks/blob/master/roles/virt-install/tasks/main.yml).

From then on it was managed via DebOps, starting with 0.8.1 and then 1.0.x until I found recently that 1.0.18 or maybe already earlier (I skipped a few releases) was failing to execute the 'ntp' role. I have backports enabled, so currently it runs `systemd-245.6-1~bpo10+1`. The `systemd-timesyncd` package is not installed. I'm explicitly using `chrony` for time keeping.

**Comment by drybjed** [comment]
Oh, that explains it. Since `systemd` 245, the `timesyncd` service has been split into [its own Debian package](https://packages.debian.org/sid/main/systemd-timesyncd). This can be seen in the [package Changelog](https://metadata.ftp-master.debian.org/changelogs//main/s/systemd/systemd_245.7-1~bpo10+1_changelog):

>   * Ship systemd-timesyncd in a separate package.
    The new systemd-timesyncd package conflicting with other NTP-related
    packages resolves the problems arising when running systemd-timesyncd
    and other NTP servers on the same system.
    (LP: #1849156, Closes: #805927, #947936)

In that case the support in DebOps needs to be updated before Bullseye is released.

I plan to split the NTP support from the `ntp` roles into separate ones (`chrony`, `timesyncd`, `openntpd`) and make the `ntp` role a ["wrapper role"](https://lists.debops.org/hyperkitty/list/debops-devel@lists.debops.org/thread/LRP4XPQATH6FNZA3TMY6A7JHQW2CGIS7/) that will let you choose between different sevice. However this will take some time.

In any case, this PR that you are proposing will not work with hosts that don't use `systemd` 245+, which includes Debian Buster. There's no Ansible local fact that provides version of the init system, so we cannot use a condition with that. Basing the condition on an OS release will also not work because you are using `systemd` from Backports. I need to think about this a bit.

**Comment by ganto** [comment]
> In any case, this PR that you are proposing will not work with hosts that don't use systemd 245+, which includes Debian Buster. 

Why is that?

**Comment by drybjed** [comment]
Scratch that - you're right, since the condition checks if the service exists or not, it should work fine. I guess we can go with that then for the time being. Do you want to rebase the PR on the current `master` branch and fix merge conflicts? I can do it otherwise.

**Review by tasosalvas — APPROVED** [review]

**Review by drybjed — APPROVED** [review]
Looks good, thanks.

**Pull request merged**
