### PR TITLE
feat(sshd): Keep SSH_CONNECTION env var when running commands with sudo

### PR DESCRIPTION
**Pull request by ypid**

### CODE REVIEW

**Review by drybjed — DISMISSED** [review]
Sounds good, although this change needs to be propagated to more playbooks, like `bootstrap-ldap`, `bootstrap-sss` and `common`, where the `sshd` role is also used. I'll do that during merging.

**Comment by ypid** [comment]
Ah, good catch. Fixed.

**Review by drybjed — APPROVED** [review]
Works as expected, thanks. I'll fix the merge conflict and make a backport.

**Comment by ypid** [comment]
You are welcome, thanks for merging.

**Pull request merged**
