### PR TITLE
add missing fqcn for dpkg_divert

### PR DESCRIPTION
**Pull request by 532910**
This is an ansible recommendation and it makes mitogen work.

### CODE REVIEW

**Review by drybjed — APPROVED** [review]
Good idea, I'll make sure to backport this to the stable release as well. Just need to investigate why `ansible-lint` complains in those specific roles first...

**Comment by 532910** [comment]
It was done with `sed -i -- 's/  dpkg_divert:$/  debops.debops.dpkg_divert:/g' **/*.yml(.)` where `(.)` plain files selector in zsh.
Moreover I already have a backport for 3.0.2 that I could pr.

**Comment by drybjed** [comment]
I've made a workaround in `ansible-lint` and the Makefile, currently testing the results. I'll do the backport from the `master` branch after the PR is merged.

**Comment by 532910** [comment]
What's up with backporting? Can I help somehow?

**Pull request merged**
