### PR TITLE
[nginx] improve documentation nginx_ocsp_resolvers

### PR DESCRIPTION
**Pull request by jankowa**
clarify that it's not only for ocsp resolving but all
  dns resolving.

### CODE REVIEW

**Comment by imrejonk** [comment]
Sounds good. I think it’s a good idea to rename the variable as well (and document the rename in the upgrade notes).

**Comment by jankowa** [comment]
> Sounds good. I think it’s a good idea to rename the variable as well (and document the rename in the upgrade notes).

I thought about this possibility too. We could use:

`nginx_resolvers`

and make a default like

`nginx_resolvers: "{{ nginx_oscp_resolvers }}"

for backword compatibility?

We find the variables only in 

`ansible/roles/nginx/defaults/main.yml`
and
`ansible/roles/nginx/tasks/main.yml`

**Comment by imrejonk** [comment]
I don't think we should go down the rabbit hole of trying to keep variable names backward-compatible. We already document all variable name changes in one place (the upgrade notes), so it is trivial for a DebOps user to just modify their inventory whenever they upgrade to the next minor release (which will be 3.1).

**Review by drybjed — APPROVED** [review]
Documentation looks good, thanks. As for the variable renaming... I guess we can wait for the `nginx` role redesign to make that move, since they will be at least namespaced with two underscores at that point.

**Pull request merged**
