### PR TITLE
Fix the error: 'dict object' has no attribute 'groovy'.

### PR DESCRIPTION
**Pull request by pedrolucasbp**
Closes issue #1654.

### CODE REVIEW

**Review by imrejonk — APPROVED** [review]
Looks good to me. The GitHub Actions failures are unrelated to your change.

**Comment by pedrolucasbp** [comment]
Thank you @imrejonk for reviewing. It's a very small Change. ;)

**Review by drybjed — APPROVED** [review]
Thanks for the fix, I'll backport it to the stable releases. We should probably update the `php` role a bit so that there's no need to add more keys over next releases. :-)

The `ansible-lint` issues should be fixed in the `master` branch, so I'm merging this PR.

**Comment by drybjed** [comment]
This PR has been merged via https://github.com/debops/debops/commit/d73dfffc6561d6aed668959bd4670aca98d4aaf6, closing.

**Pull request closed without merging**
