### PR TITLE
[1897] Fixes etckeeper role failure on first run.

### LINKED ISSUE #1897: [etckeeper] First run fails on Unstage task.
etckeeper role task main.yml, first run failure. Suspected issue with line 155: extra empty tag. Is there supposed to be another tag there or are the dashes there by mistake? Subsequent runs do not produce this failure.

TASK [etckeeper : Unstage and remove ignored files from Git index] ***********************************************************************************
fatal: [debtest]: FAILED! => changed=false 
  cmd: set -o nounset -o pipefail -o errexit && etckeeper vcs ls-files -i --exclude-standard -z | xargs -0 --no-run-if-empty etckeeper vcs rm --cached --
  delta: '0:00:00.042079'
  end: '2021-10-26 21:00:18.935315'
  msg: non-zero return code
  rc: 128
  start: '2021-10-26 21:00:18.893236'
  stderr: 'fatal: ls-files -i must be used with either -o or -c'
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>

### PR DESCRIPTION
**Pull request by schmidthausen**
Closes: #1897

### CODE REVIEW

**Comment by ypid** [comment]
Can you explain what the error on first run was and how `-c` fixes it?

**Comment by schmidthausen** [comment]
I was using a base Debian Bookworm vm (by mistake, I meant to use a Bullseye 
instance) and Debops master branch. I ran debops bootstrap, then debops. The 
play failed at this task:

TASK [etckeeper : Unstage and remove ignored files from Git index] 
***********************************************************************************
fatal: [debtest]: FAILED! => changed=false
cmd: set -o nounset -o pipefail -o errexit && etckeeper vcs ls-files -i --
exclude-standard -z | xargs -0 --no-run-if-empty etckeeper vcs rm --cached --
delta: '0:00:00.042079'
end: '2021-10-26 21:00:18.935315'
msg: non-zero return code
rc: 128
start: '2021-10-26 21:00:18.893236'
stderr: 'fatal: ls-files -i must be used with either -o or -c'
stderr_lines:
stdout: ''
stdout_lines: 

I logged in to the vm and tried both suggestions from stderr output above. -o 
didn't work but running the command with -c did. It looks like it is supposed 
to remove ssh keys from the git commit. I ran the playbook on a bullseye 
instance with -vv output and verified that the same keys were removed by this 
task. It looks like the etckeeper version in bookworm has some extra flags to 
be passed to do the same thing as in bullseye so this PR probably shouldn't be 
included in the stable version atm. Something to watch for in bookworm though, 
when it is released.

I hope this explains what happened. Please let me know if you have further 
questions.

**Comment by ypid** [comment]
Ah, you also described this in the issue #1897. I added this to the initial PR comment.

**Review by ypid — APPROVED** [review]
This change LGTM. `-c` is already the default. I have not tested on Debian 12.

**Comment by ypid** [comment]
@drybjed You can merge this. I have been using it for a while already without issues.

**Review by drybjed — APPROVED** [review]
Thanks for testing this and providing a fix. I'll backport this to the stable releases.

**Pull request merged**
